### PR TITLE
Fixes duplicate error messages for collection input field items

### LINKED ISSUE #147: Duplicate error messages for collection input field items
This happens when items of first element more then second
Here is an example

### **Configuration file**
```php
0 => [
	'name' => 'test1',
	'type' => \Zend\InputFilter\InputFilter::class,
	'test1-child' => [
		'type' => \Zend\InputFilter\CollectionInputFilter::class,
		'input_filter' => [
			'field' => [
				'type' => \Zend\InputFilter\CollectionInputFilter::class,
				'input_filter' => [
					'type' => [
						'required' => true,
						'validator' => [
							0 => [
								'name' => \Zend\Validator\Between::class,
								'options' => [],
							]
						],
					],
					'price' => [
						'required' => true,
						'validator' => [
							0 => [
								'name' => \Zend\Validator\Between::class,
								'options' => [],
							]
						],
					],
				]
			],
		]
	],
]
```

### **Sending data**

```
test1[test1-child][1][field][0][type] = 159s -> wrong data
test1[test1-child][1][field][0][price] = 15.2568s -> wrong data
test1[test1-child][1][field][1][type] = 2180s -> wrong data
test1[test1-child][1][field][1][price] = 25.2568s -> wrong data
test1[test1-child][1][field][2][type] = 2180s -> wrong data
test1[test1-child][1][field][2][price] = 25.2568s -> wrong data
test1[test1-child][1][field][4][type] = 2180s -> wrong data
test1[test1-child][1][field][4][price] = 25.2568s -> wrong data

test1[test1-child][2][field][0][type] = 159 -> corect data
test1[test1-child][2][field][0][price] = 15.2568 -> wrong data
test1[test1-child][2][field][1][type] = 2180 -> corect data
test1[test1-child][2][field][1][price] = 25.2568 -> corect data
```

### **Validation Response**

```json
"validation_messages": {
	"test1-child": {
		"1": {
			"field": [
				{
					"type": {
						"error_key": "Error message",
					},
					"price": {
						"error_key": "Error message"
					}
				},
				{
					"type": {
						"error_key": "Error message",
					},
					"price": {
						"error_key": "Error message"
					}
				},
				{
					"type": {
						"error_key": "Error message",
					},
					"price": {
						"error_key": "Error message"
					}
				},
				{
					"type": {
						"error_key": "Error message",
					},
					"price": {
						"error_key": "Error message"
					}
				}
			]
		},
		"2": {
			"field": [
				{
					"type": {
						"error_key": "Error message",
					},
					"price": {
						"error_key": "Error message"
					}
				},
				{
					"type": {
						"error_key": "Error message",
					},
					"price": {
						"error_key": "Error message"
					}
				},
				{
					"type": {
						"error_key": "Error message",
					},
					"price": {
						"error_key": "Error message"
					}
				},
				{
					"type": {
						"error_key": "Error message",
					},
					"price": {
						"error_key": "Error message"
					}
				}
			]
		},
	}
}
```

@weierophinney Can you have a look and improve this as soon as you can

### PR DESCRIPTION
**Pull request by svycka**
Fixes #147 by cleaning error messages before validation

### CODE REVIEW

**Comment by svycka** [comment]
@developer-devPHP can you test this?

**Comment by svycka** [comment]
tests failed with 7.* because of https://github.com/zendframework/zend-inputfilter/pull/141

**Comment by weierophinney** [comment]
I've rebased after merging #141 so we can see how tests go.

**Comment by weierophinney** [comment]
Yet another place where stateless validators/input filters would resolve this...

**Comment by weierophinney** [comment]
Thanks, @svycka!

**Pull request merged**
