### PR TITLE
Fixed "Empty validation message for file input when sent array for file input #184"

### PR DESCRIPTION
**Pull request by ruzann**
Create empty file structure if sent array for FileInput type field.

### CODE REVIEW

**Comment by ruzann** [comment]
#184

**Comment by froschdesign** [comment]
@ruzann 
Please check Travis because your changes breaks many existing tests. Your changes should also be covered by a component test.

**Comment by ruzann** [comment]
@froschdesign I fixed bug and also added unit test

**Comment by ruzann** [comment]
@froschdesign is there any changes I should do?

**Comment by webimpress** [comment]
@froschdesign are you happy with these changes?

**Comment by webimpress** [comment]
Thanks, @ruzann!

**Pull request closed without merging**
