### PR TITLE
Add PHP 7.2 support, drop HHVM

### PR DESCRIPTION
**Pull request by Slamdunk**
- [x] Cherry-pick https://github.com/zendframework/zend-inputfilter/pull/141
- [x] Adopt recent `.travis.yml` ZF standards ([zend-session/.travis.yml](https://github.com/zendframework/zend-session/blob/develop/.travis.yml) picked)
- [x] Drop HVVM
- [x] Test PHP 7.2
- [x] Add partial PHP 7.2 support
    1. `Fatal error: Declaration of Zend\InputFilter\CollectionInputFilter::isValid() must be compatible with Zend\InputFilter\BaseInputFilter::isValid($context = NULL) in /tmp/zend-inputfilter/src/CollectionInputFilter.php`

### CODE REVIEW

**Comment by froschdesign** [comment]
The failing tests for the nightly build is related to `Zend\Validator\EmailAddress` and [`idn_to_ascii`](http://php.net/manual/en/function.idn-to-ascii.php#refsect1-function.idn-to-ascii-changelog).

**Comment by Slamdunk** [comment]
@froschdesign thank you, https://github.com/zendframework/zend-validator/pull/175

**Comment by Slamdunk** [comment]
Note that
t
Because
https://github.com/zendframework/zend-inputfilter/blob/9569f7e18122d57b66c95ff2f02472937f26db46/composer.json#L18
And zend-validator compatibility with PHP 7.2 was introduced only in [zend-validator ^2.10](https://github.com/zendframework/zend-validator/releases/tag/release-2.10.0) release

**Comment by webimpress** [comment]
@Slamdunk Maybe then we should bump requirements in composer.json?

**Comment by Slamdunk** [comment]
This is a decision that I cannot take, only maintainers know the path of expected components support.

**Comment by MatyCZ** [comment]
Any ETA for merging this PR?

**Comment by weierophinney** [comment]
@MatyCZ I'm merging it today, but it won't release yet, as I have a PR or two I'm sitting on for the 2.8.0 release (primarily waiting for docs). This cannot release in a bugfix release, as it drops support for HHVM.

**Comment by weierophinney** [comment]
Thanks, @Slamdunk!

**Pull request merged**
